import Navbar from '@/components/Navbar'
import Head from 'next/head'
import Hero from '@/components/Hero'
import About from '@/components/About'
import Developers from '@/components/Developers'
import Subscribe from '@/components/Subscribe'
import Footer from '@/components/Footer'





export default function Home() {
  return (
    <>
      <Head>
        <title>DEFI APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <Navbar />
   <Hero />
   <About />
   <Developers />
   <Subscribe />
   <Footer />
      
   </>
  )
}
